jobhunter {
  sources = [
    {
      name    = "Simplify - Summer 2026 Internships"
      url     = "https://github.com/SimplifyJobs/Summer2026-Internships"
      enabled = true
    }, 
    {
        name    = "Simplify - New Grad Positions"
        url     = "https://github.com/SimplifyJobs/New-Grad-Positions"
        enabled = false
    }
  ]

  scheduler {
    cron = "0 0 8,18 * * ?"
  }

  db {
    path = "job-hunter.db"
  }
}